# Generated by Django 6.1 on 2026-08-27 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('current_team', models.CharField(blank=True, max_length=150)),
                ('player_role', models.CharField(choices=[('batter', 'Batter'), ('bowler', 'Bowler'), ('all_rounder', 'All-rounder'), ('wicket_keeper', 'Wicket-keeper'), ('wicket_keeper_batter', 'Wicket-keeper Batter')], max_length=30)),
                ('batting_style', models.CharField(blank=True, choices=[('right_handed', 'Right-handed'), ('left_handed', 'Left-handed')], max_length=30)),
                ('bowling_style', models.CharField(choices=[('right_arm_fast', 'Right-arm Fast'), ('right_arm_medium', 'Right-arm Medium'), ('right_arm_off_break', 'Right-arm Off Break'), ('right_arm_leg_break', 'Right-arm Leg Break'), ('left_arm_fast', 'Left-arm Fast'), ('left_arm_medium', 'Left-arm Medium'), ('left_arm_orthodox', 'Left-arm Orthodox'), ('left_arm_wrist_spin', 'Left-arm Wrist Spin'), ('none', 'Does not bowl')], default='none', max_length=40)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_image_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'players',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCareerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.PositiveIntegerField(default=0)),
                ('innings', models.PositiveIntegerField(default=0)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('highest_score', models.PositiveIntegerField(default=0)),
                ('batting_average', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('strike_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hundreds', models.PositiveIntegerField(default=0)),
                ('fifties', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('bowling_average', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('economy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('catches', models.PositiveIntegerField(default=0)),
                ('stumpings', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_stats', to='players.player')),
            ],
            options={
                'db_table': 'player_career_stats',
            },
        ),
    ]
