# Generated by Django 6.1 on 2026-08-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerExternalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricclubs_id', models.CharField(max_length=100, unique=True)),
                ('profile_url', models.URLField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cricclubs_source', to='players.player')),
            ],
            options={
                'db_table': 'player_cricclubs_sources',
            },
        ),
    ]
