# Generated by Django 6.1 on 2026-08-28 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_add_player_cricclubs_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='city',
        ),
        migrations.RemoveField(
            model_name='player',
            name='country',
        ),
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='playercareerstats',
            name='batting_average',
        ),
        migrations.RemoveField(
            model_name='playercareerstats',
            name='bowling_average',
        ),
        migrations.RemoveField(
            model_name='playercareerstats',
            name='catches',
        ),
        migrations.RemoveField(
            model_name='playercareerstats',
            name='economy_rate',
        ),
        migrations.RemoveField(
            model_name='playercareerstats',
            name='fifties',
        ),
        migrations.RemoveField(
            model_name='playercareerstats',
            name='highest_score',
        ),
        migrations.RemoveField(
            model_name='playercareerstats',
            name='hundreds',
        ),
        migrations.RemoveField(
            model_name='playercareerstats',
            name='innings',
        ),
        migrations.RemoveField(
            model_name='playercareerstats',
            name='strike_rate',
        ),
        migrations.RemoveField(
            model_name='playercareerstats',
            name='stumpings',
        ),
        migrations.CreateModel(
            name='PlayerSeriesStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_type', models.CharField(max_length=50)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('innings', models.PositiveIntegerField(default=0)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('batting_average', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('strike_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('highest_score', models.CharField(blank=True, max_length=20)),
                ('hundreds', models.PositiveIntegerField(default=0)),
                ('fifties', models.PositiveIntegerField(default=0)),
                ('bowling_innings', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('bowling_average', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('economy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('catches', models.PositiveIntegerField(default=0)),
                ('stumpings', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_stats', to='players.player')),
            ],
            options={
                'db_table': 'player_series_stats',
                'constraints': [models.UniqueConstraint(fields=('player', 'series_type'), name='unique_player_series_stats')],
            },
        ),
    ]
