# Generated by Django 6.1 on 2026-08-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_simplify_player_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerexternalsource',
            name='profile_key',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerexternalsource',
            name='profile_url',
            field=models.URLField(),
        ),
    ]
