# Generated by Django 6.1 on 2026-09-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_add_cricclubs_profile_key"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playerseriesstats",
            name="unique_player_series_stats",
        ),

        migrations.RenameField(
            model_name="player",
            old_name="current_team",
            new_name="last_bd_community_cup_team",
        ),

        migrations.AlterField(
            model_name="player",
            name="last_bd_community_cup_team",
            field=models.CharField(
                max_length=150,
                blank=True,
                default="",
            ),
        ),

        migrations.RemoveField(
            model_name="player",
            name="display_name",
        ),

        migrations.AddField(
            model_name="player",
            name="michigan_cricket_association_team",
            field=models.CharField(
                max_length=150,
                blank=True,
                default="",
            ),
        ),

        migrations.DeleteModel(
            name="PlayerSeriesStats",
        ),
    ]